<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
  <array/>
	<key>injectionSelector</key>
	<string>*</string>
	<key>name</key>
	<string>Fold Guides</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#leading-spaces</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=\t)</string>
			<key>end</key>
			<string>(?=[^\t])</string>
			<key>name</key>
			<string>meta.leading-tabs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.odd-tab</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.even-tab</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\t)(\t)?</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>leading-spaces</key>
		<dict>
			<key>begin</key>
			<string>^(?=\s\s)</string>
			<key>end</key>
			<string>(?=[^\s\s])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.odd-tab</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.even-tab</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\s\s)(\s\s)?</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>uuid</key>
	<string>5B485CC3-BF07-4B34-88CE-F61733442821</string>
</dict>
</plist>
